<?php
include "./includes/header.inc.php";
include "./includes/footer.inc.php";
include "./includes/tools.php";
require "./includes/data-validation.inc.php"; // include validation functions
require "./styles/index.css.php"; //include CSS Style Sheet
require "./styles/cart.css.php"; //include CSS Style Sheet

// preShow($_SERVER['REQUEST_METHOD']); // DEBUT
top_module("My Cart", true);
$numberError = "";
$expError = "";
$cvvError = "";

if ($_SERVER['REQUEST_METHOD'] == "POST") {
    if (isset($_POST["cardNumber"])) {
        $numberError = validate_cardNumber($_POST["cardNumber"]);
    }
    if (isset($_POST["expDate"])) {
        $expError = validate_card_expDate($_POST["expDate"]);
    }
    if (isset($_POST["cvv"])) {
        $cvvError = validate_cvvNumber($_POST["cvv"]);
    }
    if ($numberError == "" && $expError == "" && $cvvError == "") {
        echo  '<script>
            
           localStorage.clear();
        </script>';
    }
}

?>

<main>
    <div class="container-fluid mt-5">
        <div class="row row-custom">
            <div class="col-sm" style="padding: 1rem;">
                <div class="list-container">
                    <ul id="productList" style="padding: 0;">
                        <!-- Dynamic HTML generated by JS -->
                    </ul>
                </div>

            </div>
            <div class="col-sm col-md-12 col-lg-4" style="padding: 1rem;">
                <div class="order-container">
                    <h5>Total Cost: $<span id="totalCost">0</span></h5>
                    <div id="checkoutBtn">
                        <button type="button" class="btn btn-custom" style="margin-top: 2rem;" <?php
                                                                                                if (isset($_SESSION["user_name"])) {
                                                                                                    echo 'data-toggle="modal" data-target="#exampleModal"';
                                                                                                } else {
                                                                                                    echo 'onclick="redirect()"';
                                                                                                }
                                                                                                ?>>
                            Proceed to checkout
                        </button>
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div id="dialog" class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Checkout</h5>
                                    <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button> -->
                                </div>
                                <div class="modal-body" id="modalBody">
                                    <form id="checkoutForm" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                                        <div class="form-group" style="text-align:left;">
                                            <label for="address" class="small"><b>Address</b></label>
                                            <input type="text" id="address" class="form-control" placeholder="Enter your address" name="address">
                                        </div>
                                        <div class="form-group" style="text-align:left;">
                                            <label for="cardNumber" class="small"><b>Card Number</b></label>
                                            <input type="text" id="cardNumber" class="form-control" placeholder="Enter your card number" name="cardNumber">

                                            <span class="small" style="color: red;">
                                                <?php echo $numberError; ?>
                                            </span>
                                        </div>
                                        <div class="form-group" style="text-align:left;">
                                            <label for="expDate" class="small"><b>Expired Date</b></label>
                                            <input type="month" class="form-control" id="expDate" name="expDate" onClick="updateCurrentTime()">

                                            <span class="small" style="color: red;">
                                                <?php echo $expError; ?>
                                            </span>
                                        </div>
                                        <div class="form-group" style="text-align:left;">
                                            <label for="cvvNumber" class="small"><b>CVV</b></label>
                                            <input type="text" id="cvvNumber" class="form-control" placeholder="Enter your cvv number" name="cvv">

                                            <span class="small" style="color: red;">
                                                <?php echo $cvvError; ?>
                                            </span>
                                        </div>
                                    </form>
                                    <div>
                                        <div id="checkoutLoader" class="loader" style="display:none;"></div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button id="btnCloseModal" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button id="btnSubmitModal" type="button" class="btn btn-primary" onclick="sendForm()">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</main>



<?php
require "./scripts/cart.script.php";

end_module(True); // Enable Footer
if ($_SERVER['REQUEST_METHOD'] == "POST") {
    echo '<script>
            $("#exampleModal").modal();
        </script>';

    if ($numberError == "" && $expError == "" && $cvvError == "") {
        echo 'Successfully';
        echo  '<script>
            
            let btnSubmitModal = document.getElementById("btnSubmitModal");
            let modalBody = document.getElementById("modalBody");
            if (modalBody && btnSubmitModal) {
                modalBody.innerHTML = "Checkout Successfully";
                btnSubmitModal.style="display: none;";
            }
        </script>';
    }
}
?>