<?php
include "./includes/header.inc.php";
include "./includes/footer.inc.php";
include "./includes/tools.php";
require "./styles/index.css.php"; //include CSS Style Sheet
require "./styles/cart.css.php"; //include CSS Style Sheet
top_module("My Cart", true);
?>

<main>
    <div class="container-fluid">
        <div class="row row-custom">
            <div class="col-sm" style="padding: 1rem;">
                <div class="list-container">
                    <ul id="productList" style="padding: 0;">
                        <!-- Dynamic HTML generated by JS -->
                    </ul>
                </div>

            </div>
            <div class="col-sm col-md-12 col-lg-4" style="padding: 1rem;">
                <div class="order-container">
                    <h5>Total Cost: $<span id="totalCost"></span></h5>

                    <button id="checkoutBtn" type="button" class="btn btn-custom" style="margin-top: 2rem;" <?php
                                                                                                            if (isset($_SESSION["user_name"])) {
                                                                                                                echo 'data-toggle="modal" data-target="#exampleModal"';
                                                                                                            } else {
                                                                                                                echo 'onclick="redirect()"';
                                                                                                            }
                                                                                                            ?>>
                        Proceed to checkout
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form id="checkoutForm" action="./processing/checkout.pro.php" method="post">
                                        <div class="form-group">
                                            <label for="cardNumber" class="small"><b>CardNumber</b></label>
                                            <input type="text" id="cardNumber" class="form-control" placeholder="Enter your card number" name="cardNumber">
                                        </div>
                                        <div class="form-group">
                                            <label for="expDate" class="small"><b>Expired Date</b></label>
                                            <input type="month" class="form-control" id="expDate" name="expMonth">
                                        </div>
                                        <div class="form-group">
                                            <label for="cvvNumber" class="small"><b>CVV Number</b></label>
                                            <input type="text" id="cvvNumber" class="form-control" placeholder="Enter your cvv number" name="cvv">
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary" onclick="sendForm()">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</main>

<?php
require "./scripts/cart.script.php";
end_module(True); // Enable Footer
?>